# Generated by Django 4.0.6 on 2022-08-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_dailytask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='Totalhour',
            field=models.TimeField(default=0),
        ),
    ]
