# Generated by Django 4.0.6 on 2022-08-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_alter_dailytask_totalhour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailytask',
            name='Totalhour',
        ),
    ]
